version: '3'

services:
  tgbot:
    container_name: tgbot
    build: ./tgbot
    env_file:
      - tgbot/.env
    restart: unless-stopped
    networks:
      - remotesb

  backend:
    container_name: backend
    build: ./back-end
    env_file:
      - backend/.env
    restart: unless-stopped
    networks:
      -remotesb

networks:
    remotesb:
        driver: bridge